name: dingtalk_bot_sender
description: The library send message of dingtalk bot with webhook url.
version: 1.2.0
homepage: https://github.com/CaiJingLong/dingtalk_bot_sender.git

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.14.4

dependencies:
  crypto: ^3.0.1
  http: ^1.1.0
