name: dingtalk_bot_sender
description: The library send message of dingtalk bot with webhook url.
version: 1.0.0
homepage: https://github.com/CaiJingLong/dingtalk_bot_sender.git
publish_to: https://pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

dependencies:
  crypto: ^3.0.1
  http: ^0.13.3
